<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\http\\badrequesthttpresponsetest' => '/responses/BadRequestHttpResponseTest.php',
                'spriebsch\\http\\fakehttprequesttest' => '/requests/FakeHttpRequestTest.php',
                'spriebsch\\http\\htmlcontenthttpresponsetest' => '/responses/HtmlContentHttpResponseTest.php',
                'spriebsch\\http\\notfoundhttpresponsetest' => '/responses/NotFoundHttpResponseTest.php',
                'spriebsch\\http\\realhttprequesttest' => '/requests/RealHttpRequestTest.php',
                'spriebsch\\http\\redirecthttpresponsetest' => '/responses/RedirectHttpResponseTest.php',
                'spriebsch\\http\\urlpathtest' => '/requests/UrlPathTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
