<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\http\\abstracthttprequest' => '/requests/AbstractHttpRequest.php',
                'spriebsch\\http\\abstracthttpresponse' => '/responses/AbstractHttpResponse.php',
                'spriebsch\\http\\badrequesthttpresponse' => '/responses/badRequest/BadRequestHttpResponse.php',
                'spriebsch\\http\\contenthttpresponse' => '/responses/content/ContentHttpResponse.php',
                'spriebsch\\http\\fakehttprequest' => '/requests/FakeHttpRequest.php',
                'spriebsch\\http\\htmlcontenthttpresponse' => '/responses/content/HtmlContentHttpResponse.php',
                'spriebsch\\http\\httpexception' => '/HttpException.php',
                'spriebsch\\http\\httprequest' => '/requests/HttpRequest.php',
                'spriebsch\\http\\httpresponse' => '/responses/HttpResponse.php',
                'spriebsch\\http\\mediahttpresponse' => '/responses/media/MediaHttpResponse.php',
                'spriebsch\\http\\notfoundhttpresponse' => '/responses/notFound/NotFoundHttpResponse.php',
                'spriebsch\\http\\okhttpresponse' => '/responses/ok/OkHttpResponse.php',
                'spriebsch\\http\\permanentredirecthttpresponse' => '/responses/redirect/PermanentRedirectHttpResponse.php',
                'spriebsch\\http\\realhttprequest' => '/requests/RealHttpRequest.php',
                'spriebsch\\http\\redirecthttpresponse' => '/responses/redirect/RedirectHttpResponse.php',
                'spriebsch\\http\\requestmethod' => '/requests/RequestMethod.php',
                'spriebsch\\http\\temporaryredirecthttpresponse' => '/responses/redirect/TemporaryRedirectHttpResponse.php',
                'spriebsch\\http\\urlpath' => '/requests/UrlPath.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
